repo: 'interactive-polaroids'
canvasCourse: 'web-dev-4'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    locked: true

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - ['.polaroid', 'transition']
      - ['.polaroid', 'position', 'absolute']
    search:
      - 'transition'
      - 'transform\: rotate\('
      - '\.polaroid\:hover'
    searchNot:
      - 'animation'
  - path: "css/modules.css"
    locked: true

screenshots:
  - path: 'index.html'
    sizes: [960]

functionality:
  - path: "index.html"
    tests:
      - |
        let pterano = $('.polaroid:nth-child(2)');
        let oldPteranoZ = css(pterano).zIndex;
        let oldPteranoTrans = css(pterano).transform;
        let oldPteranoShadow = css(pterano).boxShadow;

        hover('.polaroid:nth-child(2)', function () {
          if (css(pterano).zIndex == oldPteranoZ) fail('The pteranodon doesn’t change `z-index` when hovered.');
          if (css(pterano).transform == oldPteranoTrans) fail('The pteranodon doesn’t rotate when hovered.');
          if (css(pterano).boxShadow == oldPteranoShadow) fail('The pteranodon doesn’t change `box-shadow` when hovered.');
          pass();
        });
